### PR TITLE
Add favicon to xsnippet

### PR DESCRIPTION
**Pull request by lotrien**
To improve user experience and let user see site symbol right next
to site title on browser tab.

### CODE REVIEW

**Review by malor — DISMISSED** [review]
I think I liked the blue one better, but white is good as well 👍

**Comment by lotrien** [comment]
Seems that we can change color to blue (but it wouldn't suit our new color palette) or black? Which one is better?

**Comment by malor** [comment]
> Seems that we can change color to blue (but it wouldn't suit our new color palette) or black? Which one is better?

Now that we use the white color on the main page, let's maybe just stick to it for the favicon as well.

**Review by ikalnytskyi — CHANGES_REQUESTED** [review]
It seems it's not copied over to `dlist/` directory.

**Review by ikalnytskyi — APPROVED** [review]
Now it's better! 👍

**Pull request merged**
